Number1=int(input("enter the first number: "))
Number2=int(input("enter the second number: "))

print("the sum is",Number1+Number2)
print("---------------------------------")
print("the subtraction is",Number1-Number2)
print("---------------------------------")
print("the multiplication is",Number1*Number2)
print("---------------------------------")
print("the division is",Number1/Number2)